/*
 * Compatibility defines for prima wlan driver on kernel 4.4
 * Maps old STATION_INFO_* and RATE_INFO_FLAGS_* to 4.4 equivalents
 */
#ifndef __WLAN_HDD_COMPAT_H
#define __WLAN_HDD_COMPAT_H

#include <linux/version.h>

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4,0,0))

#include <uapi/linux/nl80211.h>

/* STATION_INFO_* renamed to BIT(NL80211_STA_INFO_*) in 4.x */
#define STATION_INFO_SIGNAL		BIT(NL80211_STA_INFO_SIGNAL)
#define STATION_INFO_TX_BITRATE		BIT(NL80211_STA_INFO_TX_BITRATE)
#define STATION_INFO_RX_BITRATE		BIT(NL80211_STA_INFO_RX_BITRATE)
#define STATION_INFO_TX_PACKETS		BIT(NL80211_STA_INFO_TX_PACKETS)
#define STATION_INFO_TX_RETRIES		BIT(NL80211_STA_INFO_TX_RETRIES)
#define STATION_INFO_TX_FAILED		BIT(NL80211_STA_INFO_TX_FAILED)
#define STATION_INFO_RX_PACKETS		BIT(NL80211_STA_INFO_RX_PACKETS)
#define STATION_INFO_INACTIVE_TIME	BIT(NL80211_STA_INFO_INACTIVE_TIME)
#define STATION_INFO_TX_BYTES		BIT(NL80211_STA_INFO_TX_BYTES)
#define STATION_INFO_RX_BYTES		BIT(NL80211_STA_INFO_RX_BYTES)
#define STATION_INFO_SIGNAL_AVG		BIT(NL80211_STA_INFO_SIGNAL_AVG)
#define STATION_INFO_RX_DROP_MISC	BIT(NL80211_STA_INFO_RX_DROP_MISC)
#define STATION_INFO_CONNECTED_TIME	BIT(NL80211_STA_INFO_CONNECTED_TIME)
#define STATION_INFO_ASSOC_REQ_IES	0 /* removed in 4.x, field always valid */

/* RATE_INFO_FLAGS bandwidth renamed in 4.x */
#define RATE_INFO_FLAGS_40_MHZ_WIDTH	0
#define RATE_INFO_FLAGS_80_MHZ_WIDTH	0

#endif /* KERNEL >= 4.0 */

/* Stub for wcnss_get_iris_name (removed from 4.4 WCNSS driver) */
extern int wcnss_get_iris_name(char *iris_name);

#endif /* __WLAN_HDD_COMPAT_H */
